disabled_rules:
- weak_delegate
- trailing_whitespace
- unused_optional_binding
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 170
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  excluded: # excluded via string array
    - id
    - URL
    - lon
    - lat
    - dt
    - temp_min
    - temp_max
    - sea_level
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"

